apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api
  namespace: race-bib-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      containers:
        - name: ingest-api
          image: race-bib-platform/ingest-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: rbp-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-api
  namespace: race-bib-platform
spec:
  selector:
    app: ingest-api
  ports:
    - port: 80
      targetPort: 8000
